# Generated by Django 4.1.5 on 2023-02-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zip',
            new_name='zip_number',
        ),
    ]
