# Generated by Django 4.1.5 on 2023-02-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_options'),
        ('accounts', '0002_rename_zip_userprofile_zip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shop_fav',
            field=models.ManyToManyField(to='shops.shop'),
        ),
    ]
